version: "3"

networks:

  default:
    external: false
  logging_default:
    external: true

services:

  node-exporter:
    image: basi/node-exporter:v0.1.1
    networks:
      - default
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
      - /etc/hostname:/etc/host_hostname
    environment:
      - HOST_HOSTNAME=/etc/host_hostname
    command: '-collector.procfs /host/proc -collector.sysfs /host/sys -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($$|/)" -collector.textfile.directory /etc/node-exporter/ -collectors.enabled="conntrack,diskstats,entropy,filefd,filesystem,loadavg,mdadm,meminfo,netdev,netstat,stat,textfile,time,vmstat,ipvs"'
    deploy:
      mode: global


  cadvisor:
    image: google/cadvisor:v0.24.1
    networks:
      - default
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker:/var/lib/docker
    deploy:
      mode: global

  prometheus:
    image: vfarcic/prometheus-devops21
    networks:
      - default
    ports:
      - 9091:9090

  grafana:
    image: grafana/grafana:3.1.1
    networks:
      - default
      - logging_default
    ports:
      - 3000:3000
